spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://10.217.17.115:3306/dfjx_upload?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
      username: root
      password: Grand_p0ss
      initial-size: 10
      max-active: 100
      min-idle: 10
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      #Oracle需要打开注释
      #validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        #login-username: admin
        #login-password: admin
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: false
        wall:
          config:
            multi-statement-allow: true

system-params:
  # cas登录服务地址
  cas_url: http://10.10.10.41:17001/cas/login?locale=zh_CN&service=http%3A%2F%2F10.10.10.42%3A8080%2Fportal%2Fcallback%3Fclient_name%3DCasClient
  portal_url: http://10.10.10.41:17001/cas/logout?service=http%3A%2F%2F10.10.10.36%3A8090%2Fjx-kafmot%2F
  portal_app: 实时数据处理监控系统
  soap_url: http://10.10.10.42:18001/portal/intlDataSynchronizedService?wsdl
  cas_server_url_prefix: http://10.10.10.41:17001/cas
  project_url: http://10.10.10.36:8090/

#统一认证
auth:
  client:
    id: testclientid
    secret: 123456
  config:
    need: true
  login:
    url: http://auth-frontier.jxwda.bjdx.gov.cn/frontier/auth/toLogin?redirect_url=http%3a%2f%2f10.217.17.116%3a12100%2fdoc-collect%2Floginback
  logout:
    url: http://10.217.17.116:8094/cas/logout

# 数研统一认证配置
auth-url: http://172.25.13.75:31234
auth-frontier-url: http://auth-frontier.jxwda.bjdx.gov.cn