server:
  tomcat:
    uri-encoding: utf-8
  port: 8060
  servlet:
    context-path: /

spring:
  profiles:
    active: @profileActive@
  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB
      enabled: true
dfjx:
  global-session-timeout: 3600
  cluster: false
  redis:
    open: false  # 是否开启redis缓存  true开启   false关闭
  shiro:
    redis: false # true表示shiro session存到redis里，需要开启redis，才会生效【分布式场景】

app:
  path:
    work-dir: ${user.home}/dfjx-upload
    plugin: /plugin
    temp: /temp
    upload: /upload
    thumbnail: /thumb
    wechat-cert-file: