server:
  tomcat:
    uri-encoding: utf-8
  port: 8060
  servlet:
    context-path: /

spring:
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB
      enabled: true

app:
  path:
    work-dir: ${user.home}/dfjx-upload
    plugin: /plugin
    temp: /temp
    upload: /upload
    thumbnail: /thumb
    wechat-cert-file: